
version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.3
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    # login to Elastic container registry
    - eval $(aws ecr get-login --region us-east-1c --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=public.ecr.aws/g9s3e0m0/meli_prueba
    - IMAGE_TAG=1.0
    - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
    - echo Build started on `date`
    - echo installing composer..
    - composer install
    - echo creating .env file..
    - cp .env.example .env
    - echo generating app key
    - php artisan key:generate
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest "$IMAGE_URI"
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $IMAGE_URI